services:
  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - psql_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/src
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

volumes:
  psql_data: